language: java
jdk:
  - openjdk11

# only master branch에 push 되었을때 수행하도록 한다.
branches:
  only:
    - master

# gradle을 통해 의존성 받을때 cache로 남겨두어서 이후 같은 의존성은 받지 않도록 한다.
# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

# master branch push시에 실행할 script
script: "./gradlew clean build"

# Travic CI 실행 완료시 자동 알람 설정
# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - rmk1075@gmail.com

# travis CI test

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: springboot-webservice-s3-deploy # 6-3-3에서 생성한 S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    wait-until-deployed: true
    on:
      repo: rmk1075/SpringBoot_Webservice #Github 주소
      branch: master