spring:
  profiles:
    active: local # 기본 환경 선택
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

cloud:
  aws:
    stack:
      auto: false

#local 환경
---
spring:
  profiles:
    active: local
  datasource:
    data: classpath:data-h2.sql # 시작할 때 실행시킬 script
    url: jdbc:h2:mem:testdb
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true

# 운영 환경
# set1
---
#spring.profiles: set1
#spring.profiles.include: real-db

spring:
  config:
    activate:
      on-profile: set1

server:
  port: 8081

# set2
---
#spring.profiles: set2
#spring.profiles.include: real-db

spring:
  config:
    activate:
      on-profile: set2

server:
  port: 8082

---
spring:
  profiles:
    group:
      set1: set1, real-db
---
spring:
  profiles:
    group:
      set2: set1, real-db